#6 : Create login page in Angular
newklearz/project-management-application pull request #18
Opened 2021-11-10 12:22 UTC by newklearz

Create login component
     Create auth component for future routing of Login, Register and ForgetPassword

2021-11-10 12:29 UTC, newklearz commented
Login page design:
![Capture](https://user-images.githubusercontent.com/80581851/141113133-89666218-f3b1-4ce8-a861-340fba73b174.PNG)

2021-11-10 13:27 UTC, pionnegru requested changes
for styling you should consider [BEM](http://getbem.com/introduction/) its hard to read the intension. also, you can break the css in *theme.css that handles colors and decorations from *.css that just positions things

2021-11-10 13:27 UTC, pionnegru commented on project-management-application-web/src/app/auth/components/login/login.component.html
> +<div class="container login-container">
what's the difference between `container` and  `login-container` class?

2021-11-10 13:27 UTC, pionnegru commented on project-management-application-web/src/app/auth/components/login/login.component.html
> +<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
these should go in index.html

2021-11-10 13:27 UTC, pionnegru commented on project-management-application-web/src/app/auth/components/login/login.component.css
> +.login-form-1{
why append `-1`?

2021-11-10 13:27 UTC, pionnegru commented on project-management-application-web/src/app/auth/components/login/login.component.css
> +.login-form-1 .ForgetPwd{
class should not be with capitalization

2021-11-10 13:27 UTC, pionnegru commented on project-management-application-web/src/app/auth/components/login/login.component.css
> +.btnSubmit
lowercase

2021-11-10 13:27 UTC, pionnegru commented on project-management-application-web/src/app/auth/components/login/login.component.html
> +      <h3>Welcome to PMA</h3>
why does the login component has this information? you should break the app in to components and views. in this case, login should be just the component and the login view should put together other details

2021-11-10 13:27 UTC, pionnegru commented on project-management-application-web/src/app/auth/components/login/login.component.html
> +          <input type="password" class="form-control" placeholder="Your Password *" value=""/>
you should also add required attribute , not just the visual `*`.  also, maybe a toggle password visibility would be handy

2021-11-10 13:27 UTC, pionnegru commented on project-management-application-web/src/app/auth/components/login/login.component.html
> +          <input type="submit" class="btnSubmit" value="Login"/>
you have a submit action but the form doesn't handle this, I guess its work in progress?

2021-11-10 13:27 UTC, pionnegru commented on project-management-application-web/src/app/auth/auth-routing.module.ts
> +  imports: [RouterModule.forChild(routes)],
where is the root? :)

2021-11-16 11:58 UTC, Epurashu approved these changes
lgtm

2021-11-16 14:45 UTC, pionnegru commented on project-management-application-web/src/app/auth/components/login/login.component.ts
> +  text: String ='password';
better go with a `boolean`  something like `showPassword` and you just toggle the value

2021-11-16 14:45 UTC, pionnegru commented on project-management-application-web/src/app/auth/auth-routing.module.ts
> +  {path:'',redirectTo:'/login', pathMatch: 'full'}
being a child route, this should render a component not redirect from child to a main root

2021-11-18 12:47 UTC, Epurashu approved these changes

2021-11-18 12:51 UTC, merged